name: Subir APK a App Center
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-release:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
 
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Conceder permisos de ejecución a gradlew
        run: chmod +x ./gradlew
        
      - name: Construir APK
        run: ./gradlew assembleRelease
 
      - name: Distribuir APK a Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
